name: Build

trigger:
  branches:
    include:
    - master

pool:
  name: Hosted Windows Container
  demands: npm

steps:
- script: |
    npm install
  workingDirectory: ./
  displayName: 'npm install'

#- script: |
#    npm audit
#  workingDirectory: ./
#  displayName: 'npm audit'

- script: |
    npm run build
  workingDirectory: ./
  displayName: 'npm run build'

- script: |
    npm run test
  workingDirectory: ./
  displayName: 'npm run test'

- script: |
    npm pack
  workingDirectory: ./
  displayName: 'npm pack'

- task: CopyFiles@2
  displayName: 'Stage npm package'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.tgz'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    ArtifactName: npm

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: './coverage/junit.xml'

- task: PublishCodeCoverageResults@1
  inputs: 
    summaryFileLocation: './clover.xml'
    reportDirectory: './coverage'