name: Validation

trigger:
  branches:
    include:
    - master
    - releases/*

pool:
  name: Hosted Windows Container
  demands: npm

steps:
- script: |
    npm install
  workingDirectory: ./
  displayName: 'npm install'

- script: |
    npm audit
  workingDirectory: ./
  displayName: 'npm audit'

- script: |
    npm run build
  workingDirectory: ./
  displayName: 'npm run build'

- script: |
    npm run test
  workingDirectory: ./
  displayName: 'npm run test'
  