name: Validation

trigger: none

pr:
  branches:
    include:
    - master

pool:
  name: Hosted Windows Container
  demands: npm

steps:
- script: |
    npm install
  workingDirectory: ./
  displayName: 'npm install'

#- script: |
#    npm audit
#  workingDirectory: ./
#  displayName: 'npm audit'

- script: |
    npm run build-nofix
  workingDirectory: ./
  displayName: 'npm run build-nofix'

- script: |
    npm run build-changelog
  workingDirectory: ./
  displayName: 'npm run build-changelog'

- script: |
    npm run test
  workingDirectory: ./
  displayName: 'npm run test'
  
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: './coverage/junit.xml'

- task: PublishCodeCoverageResults@1
  inputs: 
    summaryFileLocation: './clover.xml'
    reportDirectory: './coverage'