# Reference: <https://help.github.com/en/actions/language-and-framework-guides/publishing-nodejs-packages>
name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    # The type of runner that the job will run on
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    
    - name: Download package
      uses: actions/download-artifact@v1
      with:
        name: package

    - run: npm install

    - name: configure npmrc
      run: npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"

    - run: npm publish ./package/final-hill-decorator-contracts.tgz
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}